version: '3.9'

services:

  db:
    image: postgres
    restart: always

    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploying via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: abishek182
    ports:
      - 5432:5432

  cricket11App:
    image: cricket11
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
    deploy:
      replicas: 2
