version: '3.9'

services:

  db:
    image: postgres
    restart: always
    container_name: postgres-db

    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - type: tmpfs
        target: /data/cricket11
        #tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: abishek182
    ports:
      - 5432:5432


  cricket11App:
    image: cricket11
    restart: always
    ports:
      - 8080:8080
    #deploy:
     # replicas: 1
